In [1]:
import torch

# 1D Tensor
tensor_1d = torch.tensor([1, 2, 3])
# 2D Tensor
tensor_2d = torch.tensor([[1, 2], [3, 4]])
# 3D Tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(tensor_2d)

tensor([[1, 2],
        [3, 4]])


In [2]:
import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3])
# 2D Array
array_2d = np.array([[1, 2], [3, 4]])
# 3D Array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array_2d)

[[1 2]
 [3 4]]


In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

add = a + b
print(add)
sub = a - b
print(sub)
mul = a * b
print(mul)
div = a / b
print(div)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [4]:
a_np = np.array([1, 2, 3])
b_np = np.array([4, 5, 6])

# NumPy
add_np = a_np + b_np
print(add_np)
sub_np = a_np - b_np
print(sub_np)
mul_np = a_np * b_np
print(mul_np)
div_np = a_np / b_np
print(div_np)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [5]:
# Dot product (1D)
dot_pt = torch.dot(a, b)
dot_np = np.dot(a_np, b_np)
print(dot_pt)
print(dot_np)

# Matrix Multiplication (2D)
mat1 = torch.tensor([[1, 2], [3, 4]])
mat2 = torch.tensor([[5, 6], [7, 8]])
matmul_pt = torch.matmul(mat1, mat2)

mat1_np = np.array([[1, 2], [3, 4]])
mat2_np = np.array([[5, 6], [7, 8]])
matmul_np = np.matmul(mat1_np, mat2_np)

print(matmul_pt)
print(matmul_np)

tensor(32)
32
tensor([[19, 22],
        [43, 50]])
[[19 22]
 [43 50]]


In [6]:
x = torch.tensor([[10, 20, 30], [40, 50, 60]])

# Extract row
row = x[1]
print(row)
# Extract column
col = x[:, 1]
print(col)
# Boolean Masking
mask = x > 25
masked = x[mask]
print(masked)

tensor([40, 50, 60])
tensor([20, 50])
tensor([30, 40, 50, 60])


In [7]:
x_np = np.array([[10, 20, 30], [40, 50, 60]])
row_np = x_np[1]
print(row_np)
col_np = x_np[:, 1]
print(col_np)
masked_np = x_np[x_np > 25]
print(masked_np)

[40 50 60]
[20 50]
[30 40 50 60]


In [8]:
x = torch.arange(6)

reshaped = x.reshape(2, 3)

unsqueezed = x.unsqueeze(0) 

squeezed = unsqueezed.squeeze() 

viewed = x.view(2, 3)  #need continuous data

In [9]:
x_np = np.arange(6)
reshaped_np = x_np.reshape(2, 3)

In [10]:
# PyTorch
a = torch.tensor([[1], [2], [3]])  # shape (3,1)
b = torch.tensor([4, 5, 6])        # shape (3,)
result = a + b  
print(result.size())

# NumPy
a_np = np.array([[1], [2], [3]])
b_np = np.array([4, 5, 6])
result_np = a_np + b_np

torch.Size([3, 3])


In [11]:
x = torch.tensor([1.0, 2.0, 3.0])

# Out-of-place (returns a new tensor)
y = x + 1
print(y)

# In-place (modifies the original tensor)
x.add_(1)  
print(x)

tensor([2., 3., 4.])
tensor([2., 3., 4.])


In [12]:
arr = np.array([1.0, 2.0, 3.0])

# Out-of-place
arr2 = arr + 1

# In-place
arr += 1